### ISSUE TITLE
License compatible logos/images

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/WorkshopPrace2021#27]
Before we publicly release the materials we need to make sure that everything we have is license compatible.

I think the biggest question is: is the MDA logo CC-BY-4-SA compatible? (pinging @orbeckst and @jbarnoud here who might have a better idea of the MDA logo's licensing and cross CC-BY version compatibility).

The other one is whether the logos used in the first lecture are all suitable license-wise. @fiona-naughton can you check this?

**Comment by jbarnoud** [comment]
I'd say, but I am no legal expert, that logos are a "fair use" thing (there nothing names like that in UK or EU law from what I know, but there are equivalent concepts). Basically: the use is legitimate regardless of the license. We may have to put a note about them somewhere, though. Otherwise, it is not like they add much to the content so wiping them out is fine by me.

**Comment by orbeckst** [comment]
We license the logo under Cc-by-nd; I’d also argue that it’s ok to include it with this exception. Note hat we don’t want someone to slap, say, a superhero, on it and use it for their project. Hypothetically speaking.

**Comment by orbeckst** [comment]
(We can do with our logo whatever we want, it’s ours.)

**Comment by IAlibay** [comment]
I guess probably the easiest thing we could do is just copy in the logo part of the license from the MDA core library?
